"""Decide whether a discovered file is APM's or the user's.

Evidence, in priority order: the lockfile's deployed-file claims, recorded
content hashes for format-transformed rule files, APM generation markers in
compiled context files, per-entry hook markers (resolved by the hooks scanner)
and lockfile MCP ownership. Anything else is host-owned.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath

from apm_cli.compilation.claude_formatter import CLAUDE_HEADER
from apm_cli.compilation.distributed_compiler import AGENTS_MD_GENERATED_MARKER
from apm_cli.core.deployment_ledger import DeploymentLedgerCodec
from apm_cli.core.scope import USER_APM_DIR
from apm_cli.deps.lockfile import LockFile, resolve_lockfile_path_for_read
from apm_cli.integration.base_integrator import BaseIntegrator
from apm_cli.integration.instruction_integrator import InstructionIntegrator
from apm_cli.integration.targets import RULE_FORMATS
from apm_cli.utils.content_hash import compute_file_hash

from .model import HarnessKind, Ownership, RawFinding, Scope
from .provenance import ImportSources
from .registry import probe_text

_GENERATED_PREFIX = "<!-- Generated by APM CLI"
_MANAGED_START = "<!-- apm:start -->"
_GENERATED_MARKERS: tuple[str, ...] = (
    CLAUDE_HEADER,
    AGENTS_MD_GENERATED_MARKER,
    InstructionIntegrator._APM_COPILOT_HEADER,
    _GENERATED_PREFIX,
)


@dataclass
class OwnershipIndex:
    """Lockfile-derived knowledge about what APM has deployed in one scope."""

    root: Path
    scope: Scope
    managed_files: frozenset[str] = frozenset()
    file_hashes: dict[str, str] = field(default_factory=dict)
    mcp_owned: frozenset[str] = frozenset()
    source_stems: frozenset[str] = frozenset()
    import_sources: frozenset[str] = frozenset()
    lockfile_present: bool = False

    @classmethod
    def build(cls, root: Path, scope: Scope) -> OwnershipIndex:
        """Read the lockfile for *scope* and index its claims."""
        lock_dir = root if scope is Scope.PROJECT else root / USER_APM_DIR
        apm_dir = lock_dir / ".apm" if scope is Scope.PROJECT else lock_dir
        lockfile: LockFile | None = None
        try:
            lock_path = resolve_lockfile_path_for_read(lock_dir, read_only=True)
            if lock_path.is_file():
                lockfile = LockFile.read(lock_path)
        except Exception:  # malformed lockfile must not abort a read-only scan
            lockfile = None
        index = cls(root=root, scope=scope)
        index.source_stems = frozenset(_source_instruction_stems(root, lockfile))
        index.import_sources = frozenset(
            record.source for record in ImportSources.load(apm_dir).entries.values()
        )
        if lockfile is None:
            return index
        claims = DeploymentLedgerCodec.legacy_deployed_file_claims(lockfile)
        normalized = BaseIntegrator.normalize_managed_files(set(claims)) or set()
        hashes: dict[str, str] = {}
        for dependency in lockfile.dependencies.values():
            hashes.update(dependency.deployed_file_hashes or {})
        hashes.update(lockfile.local_deployed_file_hashes or {})
        index.managed_files = frozenset(normalized)
        index.file_hashes = {k.replace("\\", "/"): v for k, v in hashes.items()}
        index.mcp_owned = frozenset(lockfile.mcp_configs) | frozenset(lockfile.mcp_servers)
        index.lockfile_present = True
        return index

    # -- helpers -----------------------------------------------------------

    def relative(self, path: Path) -> str | None:
        try:
            return PurePosixPath(
                path.resolve(strict=False).relative_to(self.root.resolve(strict=False))
            ).as_posix()
        except ValueError:
            return None

    def _is_managed(self, rel: str, is_dir: bool) -> bool:
        if rel in self.managed_files:
            return True
        if is_dir:
            prefix = rel + "/"
            return any(m.startswith(prefix) for m in self.managed_files)
        return False

    def _hash_matches(self, rel: str, path: Path) -> bool:
        recorded = self.file_hashes.get(rel)
        if not recorded:
            return False
        try:
            actual = compute_file_hash(path)
        except OSError:
            return False
        return recorded.removeprefix("sha256:") == actual.removeprefix("sha256:")

    @staticmethod
    def _marker_state(path: Path) -> str | None:
        head = probe_text(path)
        if head is None:
            return None
        text = head.decode("utf-8", errors="ignore")
        if any(marker in text for marker in _GENERATED_MARKERS):
            return "generated"
        if _MANAGED_START in text:
            return "managed-section"
        return None

    # -- decision ----------------------------------------------------------

    def decide(self, raw: RawFinding) -> tuple[Ownership, tuple[str, ...]]:
        """Return the ownership of *raw* and the evidence that justified it."""
        if raw.ownership is not None:
            return raw.ownership, ()
        if raw.kind is HarnessKind.MCP_SERVER:
            name = (raw.payload or {}).get("name") if isinstance(raw.payload, dict) else None
            if name and name in self.mcp_owned:
                return Ownership.APM_OWNED, ("lockfile:mcp_configs",)
            return Ownership.HOST_OWNED, ()
        if raw.abs_path is None:
            return Ownership.HOST_OWNED, ()
        rel = self.relative(raw.abs_path)
        is_dir = raw.abs_path.is_dir()
        if rel is not None and self._is_managed(rel, is_dir):
            return Ownership.APM_OWNED, ("lockfile:managed_files",)
        if is_dir:
            return Ownership.HOST_OWNED, ()
        if rel is not None and raw.format_id in RULE_FORMATS:
            if self._hash_matches(rel, raw.abs_path):
                return Ownership.APM_OWNED, ("lockfile:hash-match",)
            stem = PurePosixPath(rel).name.split(".")[0]
            if stem in self.source_stems:
                if raw.display_path in self.import_sources:
                    return Ownership.HOST_OWNED, ("provenance:re-import-source",)
                return Ownership.AMBIGUOUS, ("name:matches-source-instruction",)
        if raw.kind in (HarnessKind.ROOT_CONTEXT, HarnessKind.INSTRUCTION, HarnessKind.RULE):
            state = self._marker_state(raw.abs_path)
            if state == "generated":
                return Ownership.APM_GENERATED, ("marker:generated-by-apm",)
            if state == "managed-section":
                return Ownership.AMBIGUOUS, ("marker:apm-managed-section",)
        return Ownership.HOST_OWNED, ()


def _source_instruction_stems(root: Path, lockfile: LockFile | None) -> Iterable[str]:
    """Stems of instruction sources whose deployed rule files APM owns 1:1."""
    dirs = [root / ".apm" / "instructions"]
    if lockfile is not None:
        modules = root / "apm_modules"
        for installed in lockfile.get_installed_paths(modules):
            dirs.append(Path(installed) / ".apm" / "instructions")
    for directory in dirs:
        if not directory.is_dir():
            continue
        for file in directory.glob("*.instructions.md"):
            yield file.name.split(".")[0]
