"""Root context files (CLAUDE.md, AGENTS.md, GEMINI.md, .cursorrules, ...) -> instruction."""

from __future__ import annotations

import re
from pathlib import Path, PurePosixPath

from apm_cli.utils.path_security import PathTraversalError, ensure_path_within

from ..model import Finding
from . import ConvertContext, ConvertError, ConvertResult
from .base import emit_markdown, read_text
from .rules import ALWAYS_ON

MANAGED_START = "<!-- apm:start -->"
MANAGED_END = "<!-- apm:end -->"
_IMPORT_LINE = re.compile(r"^@(?P<target>\S+)\s*$")


def strip_managed_section(text: str, result: ConvertResult) -> str:
    """Remove exactly one APM managed section; refuse ambiguous marker layouts."""
    starts = text.count(MANAGED_START)
    ends = text.count(MANAGED_END)
    if starts == 0 and ends == 0:
        return text
    if starts != 1 or ends != 1:
        raise ConvertError("unbalanced apm:start/apm:end markers")
    begin = text.index(MANAGED_START)
    finish = text.index(MANAGED_END) + len(MANAGED_END)
    if finish < begin:
        raise ConvertError("apm:end precedes apm:start")
    result.drop("body.managed_section", "APM-managed block is regenerated by apm compile")
    return text[:begin].rstrip("\n") + "\n\n" + text[finish:].lstrip("\n")


def rewrite_imports(text: str, source_dir: Path, project_root: Path, result: ConvertResult) -> str:
    """Rewrite Claude ``@path`` import lines into links; drop escaping ones."""
    out: list[str] = []
    for line in text.splitlines():
        match = _IMPORT_LINE.match(line.strip())
        if not match:
            out.append(line)
            continue
        target = match.group("target")
        if target.startswith("~") or Path(target).is_absolute():
            result.drop(
                f"body.import[{target}]",
                "machine-local import path removed",
            )
            continue
        candidate = (source_dir / target).resolve(strict=False)
        try:
            ensure_path_within(candidate, project_root.resolve(strict=False))
        except PathTraversalError:
            result.drop(f"body.import[{target}]", "import escapes the project; removed")
            continue
        if (source_dir / target).is_symlink() or not candidate.exists():
            result.drop(f"body.import[{target}]", "import target missing or symlinked; removed")
            continue
        rel = PurePosixPath(candidate.relative_to(project_root.resolve(strict=False)).as_posix())
        out.append(f"See [{rel}]({rel}).")
        result.transform(f"body.import[{target}]", "Claude @import rewritten as a link")
    return "\n".join(out) + ("\n" if text.endswith("\n") else "")


class RootContextConverter:
    """Import a hand-authored root context file as an always-on instruction."""

    id = "root_context->instruction"

    def handles(self, converter_id: str) -> bool:
        return converter_id == self.id

    def convert(self, finding: Finding, dest: Path, *, ctx: ConvertContext) -> ConvertResult:
        if finding.abs_path is None:
            raise ConvertError("no source path")
        text = read_text(finding.abs_path, ctx.limits.max_file_bytes)
        result = ConvertResult()
        text = strip_managed_section(text, result)
        if finding.tool == "claude":
            text = rewrite_imports(text, finding.abs_path.parent, ctx.project_root, result)
        if not text.strip():
            raise ConvertError("nothing left to import after removing managed content")
        basename = PurePosixPath(finding.display_path).name
        metadata = {"description": f"Project instructions imported from {basename}"}
        result.default("frontmatter.description", "generated from source filename")
        nested_dir = PurePosixPath(finding.display_path).parent
        if str(nested_dir) not in ("", ".") and not str(nested_dir).startswith("."):
            metadata["applyTo"] = f"{nested_dir.as_posix()}/**"
            result.transform("frontmatter.applyTo", "nested context file scoped to its directory")
        else:
            metadata["applyTo"] = ALWAYS_ON
            result.default("frontmatter.applyTo", "root context is always-on; applyTo: '**'")
        emit_markdown(dest, metadata, text)
        result.written.append(dest)
        return result


CONVERTERS = (RootContextConverter(),)
