"""Fixtures for brownfield discovery tests."""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

FAKE_TOKEN = "ghp_FAKEFAKEFAKEFAKEFAKEFAKEFAKE1234"


def write(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


@pytest.fixture(autouse=True)
def _quiet_update_notice(monkeypatch: pytest.MonkeyPatch) -> None:
    """Keep stdout machine-clean: the update banner would break --format json."""
    monkeypatch.setenv("APM_E2E_TESTS", "1")


@pytest.fixture
def mixed_project(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """A project with Claude, Cursor, Copilot and shared-skill context files."""
    root = tmp_path / "project"
    root.mkdir()
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setattr(Path, "home", classmethod(lambda cls: home))
    write(
        root / ".claude/rules/python.md", '---\npaths:\n  - "src/**/*.py"\n---\nUse type hints.\n'
    )
    write(
        root / ".claude/agents/reviewer.md",
        "---\nname: reviewer\ndescription: Reviews code\ntools: Read, Grep\ncolor: blue\n---\nYou review.\n",
    )
    write(
        root / ".claude/commands/frontend/fix.md",
        "---\ndescription: Fix lint\nallowed-tools: Bash\n---\nRun the linter on $ARGUMENTS\n",
    )
    write(
        root / ".claude/skills/deploy/SKILL.md",
        "---\nname: deploy\ndescription: Deploy\n---\n# Deploy\n",
    )
    write(root / ".claude/hooks/notify.sh", "#!/bin/sh\necho hi\n")
    settings = {
        "permissions": {},
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "Bash",
                    "hooks": [
                        {
                            "type": "command",
                            "command": '"$CLAUDE_PROJECT_DIR"/.claude/hooks/notify.sh',
                        }
                    ],
                },
                {
                    "matcher": "Write",
                    "hooks": [{"type": "command", "command": "echo apm"}],
                    "_apm_source": "pkg-x",
                },
            ]
        },
    }
    write(root / ".claude/settings.json", json.dumps(settings))
    mcp = {
        "mcpServers": {
            "github": {
                "command": "npx",
                "args": ["-y", "@modelcontextprotocol/server-github"],
                "env": {"GITHUB_TOKEN": FAKE_TOKEN, "GITHUB_TOOLSETS": "context"},
            },
            "remote": {"type": "http", "url": "https://user:pw@example.com/mcp?token=abc"},
        }
    }
    write(root / ".mcp.json", json.dumps(mcp))
    write(
        root / ".cursor/rules/style.mdc",
        '---\ndescription: Style\nglobs: "**/*.ts"\nalwaysApply: false\n---\nUse semicolons.\n',
    )
    write(
        root / ".github/instructions/docs.instructions.md",
        '---\napplyTo: "**/*.md"\n---\nWrite docs.\n',
    )
    write(
        root / ".agents/skills/shared-skill/SKILL.md",
        "---\nname: shared-skill\ndescription: Shared\n---\nbody\n",
    )
    write(root / "CLAUDE.md", "# Project\nHand-authored notes.\n@README.md\n")
    write(root / "README.md", "# Readme\n")
    write(root / "AGENTS.md", "<!-- Generated by APM CLI -->\n# AGENTS\n")
    (root / ".claude/rules/binary.md").write_bytes(b"x\x00y")
    if os.name != "nt":
        (root / ".cursor/rules/escape.mdc").symlink_to(tmp_path / "outside.mdc")
        write(tmp_path / "outside.mdc", "outside\n")
    return root


@pytest.fixture
def in_project(mixed_project: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    monkeypatch.chdir(mixed_project)
    return mixed_project
