"""Scanner rule derivation, classification table and ownership decisions."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from apm_cli.adopt import discover, scan_targets
from apm_cli.adopt.classify import classification_rows, classify, proposed_destination
from apm_cli.adopt.model import HarnessKind, Importability, Ownership, RawFinding, Scope
from apm_cli.adopt.ownership import OwnershipIndex
from apm_cli.adopt.registry import ScanRule
from apm_cli.adopt.scanners.profile_files import derive_rules, rules_for_targets

pytestmark = pytest.mark.component


@pytest.mark.parametrize(
    ("kind", "display_path", "expected"),
    [
        (
            HarnessKind.COMMAND,
            ".claude/commands/frontend/deploy.md",
            "prompts/frontend-deploy.prompt.md",
        ),
        (
            HarnessKind.RULE,
            ".claude/rules/Style Guide.md",
            "instructions/style-guide.instructions.md",
        ),
        (HarnessKind.AGENT, "~/.claude/agents/team/review.md", "agents/team-review.agent.md"),
        (HarnessKind.SKILL, ".claude/skills/My_Skill", "skills/my-skill/SKILL.md"),
        (
            HarnessKind.ROOT_CONTEXT,
            "src/team/sub/CLAUDE.md",
            "instructions/sub-claude-root.instructions.md",
        ),
        (HarnessKind.HOOK, ".claude/hooks/check.json", "hooks/claude-check-native.json"),
    ],
)
def test_preview_destination_uses_apply_naming(
    kind: HarnessKind, display_path: str, expected: str
) -> None:
    """Inventory paths use the writer's normalization before collision allocation."""
    raw = RawFinding("claude", Scope.PROJECT, kind, display_path, abs_path=Path(display_path))
    assert proposed_destination(raw) == f".apm/{expected}"


def test_every_static_target_primitive_yields_a_rule():
    for scope in (Scope.PROJECT, Scope.USER):
        for profile in scan_targets(scope):
            rules = derive_rules(profile)
            covered = {r.primitive for r in rules}
            for primitive in profile.primitives:
                if primitive == "hooks" and profile.name in (
                    "claude",
                    "cursor",
                    "codex",
                    "gemini",
                    "antigravity",
                    "windsurf",
                ):
                    continue  # merged-config hooks are read by the hooks scanner
                assert primitive in covered, (profile.name, scope, primitive)


def test_rules_never_use_recursive_globstar():
    rules = rules_for_targets(scan_targets(Scope.PROJECT))
    assert rules
    assert all("**" not in r.relative_glob for r in rules)
    with pytest.raises(ValueError):
        ScanRule(tool="x", kind=HarnessKind.RULE, relative_glob=".x/**/*.md")


def test_shared_skill_root_collapses_to_one_shared_rule():
    rules = rules_for_targets(scan_targets(Scope.PROJECT))
    shared = [r for r in rules if r.relative_glob == ".agents/skills/*/SKILL.md"]
    assert len(shared) == 1
    assert shared[0].tool == "shared"
    assert shared[0].directory == ".agents/skills"
    assert shared[0].pattern == "*/SKILL.md"


def test_classification_table_covers_every_kind():
    kinds = {kind for (_tool, kind) in classification_rows()}
    assert kinds == set(HarnessKind)


def test_apm_owned_forces_ignored():
    raw = RawFinding(
        "cursor", Scope.PROJECT, HarnessKind.RULE, ".cursor/rules/x.mdc", format_id="cursor_rules"
    )
    assert classify(raw, Ownership.HOST_OWNED).importability is Importability.CONVERTIBLE
    assert classify(raw, Ownership.APM_OWNED).importability is Importability.IGNORED
    assert classify(raw, Ownership.APM_GENERATED).converter_id is None


def test_ownership_from_lockfile_hash_and_markers(tmp_path: Path):
    root = tmp_path
    (root / ".cursor/rules").mkdir(parents=True)
    rule = root / ".cursor/rules/x.mdc"
    rule.write_text("---\nglobs: a\n---\nbody\n", encoding="utf-8")
    from apm_cli.utils.content_hash import compute_file_hash

    lock = {
        "lockfile_version": "1",
        "dependencies": [
            {
                "repo_url": "github.com/o/pkg",
                "name": "pkg",
                "version": "1.0.0",
                "resolved_commit": "a" * 40,
                "deployed_files": [".github/instructions/managed.instructions.md"],
                "deployed_file_hashes": {".cursor/rules/x.mdc": compute_file_hash(rule)},
            }
        ],
    }
    import yaml

    (root / "apm.lock.yaml").write_text(yaml.safe_dump(lock), encoding="utf-8")
    (root / ".github/instructions").mkdir(parents=True)
    managed = root / ".github/instructions/managed.instructions.md"
    managed.write_text("x\n", encoding="utf-8")
    (root / "CLAUDE.md").write_text("<!-- Generated by APM CLI -->\nx\n", encoding="utf-8")
    (root / "AGENTS.md").write_text(
        "intro\n<!-- apm:start -->\nx\n<!-- apm:end -->\n", encoding="utf-8"
    )

    index = OwnershipIndex.build(root, Scope.PROJECT)
    assert index.lockfile_present
    owned = RawFinding("copilot", Scope.PROJECT, HarnessKind.INSTRUCTION, "x", abs_path=managed)
    assert index.decide(owned)[0] is Ownership.APM_OWNED
    hashed = RawFinding(
        "cursor", Scope.PROJECT, HarnessKind.RULE, "x", abs_path=rule, format_id="cursor_rules"
    )
    assert index.decide(hashed)[0] is Ownership.APM_OWNED
    generated = RawFinding(
        "claude", Scope.PROJECT, HarnessKind.ROOT_CONTEXT, "CLAUDE.md", abs_path=root / "CLAUDE.md"
    )
    assert index.decide(generated)[0] is Ownership.APM_GENERATED
    mixed = RawFinding(
        "root", Scope.PROJECT, HarnessKind.ROOT_CONTEXT, "AGENTS.md", abs_path=root / "AGENTS.md"
    )
    assert index.decide(mixed)[0] is Ownership.AMBIGUOUS


def test_discover_mixed_project_reports_everything(mixed_project: Path):
    report = discover(mixed_project, Scope.PROJECT)
    by_path = {f.display_path: f for f in report.findings}
    assert by_path[".claude/rules/python.md"].importability is Importability.CONVERTIBLE
    assert by_path[".cursor/rules/style.mdc"].converter_id == "cursor_rules->instruction"
    assert (
        by_path[".github/instructions/docs.instructions.md"].importability
        is Importability.APM_NATIVE
    )
    assert by_path[".claude/skills/deploy"].kind is HarnessKind.SKILL
    assert by_path[".agents/skills/shared-skill"].tool == "shared"
    assert by_path["AGENTS.md"].ownership is Ownership.APM_GENERATED
    assert by_path["AGENTS.md"].importability is Importability.IGNORED
    assert by_path["CLAUDE.md"].importability is Importability.CONVERTIBLE
    hook = by_path[".claude/settings.json"]
    assert hook.kind is HarnessKind.HOOK and hook.ownership is Ownership.HOST_OWNED
    assert "apm-owned entries skipped: 1" in " ".join(hook.notes)
    script = by_path[".claude/hooks/notify.sh"]
    assert script.kind is HarnessKind.HOOK_SCRIPT
    assert script.importability is Importability.REFERENCE_ONLY
    mcp = by_path[".mcp.json#github"]
    assert mcp.kind is HarnessKind.MCP_SERVER
    assert set(report.detected_tools) >= {"claude", "cursor", "copilot"}
    assert list(report.proposed_targets) == ["claude", "copilot", "cursor"]
    reasons = {e.display_path: e.reason for e in report.errors}
    assert reasons[".claude/rules/binary.md"] == "binary or unreadable"
    if ".cursor/rules/escape.mdc" in reasons:
        assert "symlink" in reasons[".cursor/rules/escape.mdc"]
    assert json.dumps(report.to_dict())  # serialisable


def test_report_never_leaks_secrets_or_home(mixed_project: Path):
    from tests.unit.adopt.conftest import FAKE_TOKEN

    report = discover(mixed_project, Scope.PROJECT)
    from apm_cli.adopt.render import report_to_json, report_to_yaml

    for rendered in (report_to_json(report), report_to_yaml(report)):
        assert FAKE_TOKEN not in rendered
        assert "user:pw@" not in rendered
        assert str(mixed_project) not in rendered


def test_hook_scripts_detected_behind_interpreters(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    """`uv run script.py --flag` and `python3 script.py` both reference in-project scripts."""
    import json

    root = tmp_path / "p"
    (root / ".claude/hooks").mkdir(parents=True)
    for name in ("a.py", "b.py"):
        (root / ".claude/hooks" / name).write_text("print(1)\n", encoding="utf-8")
    settings = {
        "hooks": {
            "PreToolUse": [
                {
                    "hooks": [
                        {
                            "type": "command",
                            "command": "uv run $CLAUDE_PROJECT_DIR/.claude/hooks/a.py --notify",
                        }
                    ]
                }
            ],
            "Stop": [{"hooks": [{"type": "command", "command": "python3 .claude/hooks/b.py"}]}],
        }
    }
    (root / ".claude/settings.json").write_text(json.dumps(settings), encoding="utf-8")
    monkeypatch.setattr(Path, "home", classmethod(lambda cls: tmp_path / "home"))
    report = discover(root, Scope.PROJECT)
    scripts = sorted(f.display_path for f in report.findings if f.kind is HarnessKind.HOOK_SCRIPT)
    assert scripts == [".claude/hooks/a.py", ".claude/hooks/b.py"]
